# `flutter pub publish` to publishing
name: server_driven_ui
description: Server Driven UI Package for Flutter. New features to be deployed on all platforms simultaneously via a backend change, without releasing new versions of the native apps.
version: 0.0.5
platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  http_parser: ^4.0.2

repository: https://github.com/rhea-so-lab/flutter-server-driven-ui
documentation: https://github.com/rhea-so-lab/flutter-server-driven-ui/wiki
